title = "Critically Caring"
base_url = "/"
description = "Resources to support residents in ICU"

generate_feeds = true
compile_sass = false
build_search_index = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[markdown]

[extra]
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = true
hide_made_with_line = true

[extra.table_of_contents]
show = true
max_level = 3
visible_on_load = true

[[extra.main_menu]]
name = "About"
url = "@/_index.md"

[[extra.main_menu]]
name = "Links"
url = "@/links.md"

[[extra.main_menu]]
name = "Publications"
url = "@/publications.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
